/**
 * UnifiedPicker Emoji & Color Data
 *
 * 500+ emojis across 10 categories with full keyword search support.
 * Complete coverage similar to Microsoft Teams emoji picker.
 */

// ---------------------------------------------------------------------------
// EMOJI DATA — 500+ emojis across 10 categories, each with keywords
// ---------------------------------------------------------------------------
export const EMOJI_DATA = {
  smileys: {
    label: '😊 Smileys',
    icon: '😊',
    emojis: [
      { emoji: '😀', keywords: ['grinning', 'happy', 'smile'] },
      { emoji: '😃', keywords: ['grinning', 'eyes', 'happy'] },
      { emoji: '😄', keywords: ['grin', 'smile', 'happy', 'joy'] },
      { emoji: '😁', keywords: ['beaming', 'grin', 'smile'] },
      { emoji: '😆', keywords: ['laughing', 'squint', 'lol'] },
      { emoji: '😅', keywords: ['sweat', 'smile', 'nervous', 'relief'] },
      { emoji: '🤣', keywords: ['rofl', 'laughing', 'rolling'] },
      { emoji: '😂', keywords: ['joy', 'tears', 'laughing', 'lol'] },
      { emoji: '🙂', keywords: ['slightly smiling', 'okay', 'fine'] },
      { emoji: '🙃', keywords: ['upside down', 'sarcasm', 'silly'] },
      { emoji: '😉', keywords: ['wink', 'flirt', 'playful'] },
      { emoji: '😊', keywords: ['blush', 'happy', 'warm', 'smile'] },
      { emoji: '😇', keywords: ['angel', 'halo', 'innocent', 'good'] },
      { emoji: '🥰', keywords: ['love', 'hearts', 'adore', 'affection'] },
      { emoji: '😍', keywords: ['heart eyes', 'love', 'crush'] },
      { emoji: '🤩', keywords: ['star struck', 'excited', 'wow'] },
      { emoji: '😘', keywords: ['kiss', 'love', 'blow kiss'] },
      { emoji: '😗', keywords: ['kiss', 'whistle', 'smooch'] },
      { emoji: '😚', keywords: ['kiss', 'blush', 'closed eyes'] },
      { emoji: '😙', keywords: ['kiss', 'smiling eyes'] },
      { emoji: '😋', keywords: ['yummy', 'delicious', 'tongue'] },
      { emoji: '😛', keywords: ['tongue', 'playful', 'tease'] },
      { emoji: '😜', keywords: ['wink', 'tongue', 'crazy', 'zany'] },
      { emoji: '🤪', keywords: ['zany', 'wild', 'crazy', 'goofy'] },
      { emoji: '😝', keywords: ['tongue', 'squint', 'playful'] },
      { emoji: '🤑', keywords: ['money', 'rich', 'dollar'] },
      { emoji: '🤗', keywords: ['hug', 'warm', 'open arms'] },
      { emoji: '🤭', keywords: ['giggle', 'oops', 'cover mouth'] },
      { emoji: '🤫', keywords: ['shush', 'quiet', 'secret'] },
      { emoji: '🤔', keywords: ['thinking', 'hmm', 'curious'] },
      { emoji: '🤐', keywords: ['zipper', 'quiet', 'lips sealed'] },
      { emoji: '🤨', keywords: ['raised brow', 'skeptical', 'doubt'] },
      { emoji: '😐', keywords: ['neutral', 'meh', 'blank'] },
      { emoji: '😑', keywords: ['expressionless', 'blank', 'unimpressed'] },
      { emoji: '😶', keywords: ['mouthless', 'speechless', 'silent'] },
      { emoji: '😏', keywords: ['smirk', 'flirt', 'suggestive'] },
      { emoji: '😒', keywords: ['unamused', 'annoyed', 'side eye'] },
      { emoji: '🙄', keywords: ['eye roll', 'annoyed', 'whatever'] },
      { emoji: '😬', keywords: ['grimace', 'awkward', 'cringe'] },
      { emoji: '🤥', keywords: ['liar', 'pinocchio', 'lying'] },
      { emoji: '😌', keywords: ['relieved', 'peaceful', 'calm'] },
      { emoji: '😔', keywords: ['pensive', 'sad', 'thoughtful'] },
      { emoji: '😪', keywords: ['sleepy', 'tired', 'snot'] },
      { emoji: '🤤', keywords: ['drool', 'yummy', 'hungry'] },
      { emoji: '😴', keywords: ['sleeping', 'zzz', 'tired'] },
      { emoji: '😷', keywords: ['mask', 'sick', 'covid'] },
      { emoji: '🤒', keywords: ['thermometer', 'sick', 'fever'] },
      { emoji: '🤧', keywords: ['sneeze', 'sick', 'tissue'] },
      { emoji: '🥵', keywords: ['hot', 'sweating', 'overheated'] },
      { emoji: '🥶', keywords: ['cold', 'frozen', 'freezing'] },
      { emoji: '🥴', keywords: ['woozy', 'drunk', 'dizzy'] },
      { emoji: '😵', keywords: ['dizzy', 'knocked out', 'dead'] },
      { emoji: '🤯', keywords: ['mind blown', 'exploding head', 'shocked'] },
      { emoji: '🤠', keywords: ['cowboy', 'hat', 'western'] },
      { emoji: '🥳', keywords: ['party', 'celebration', 'birthday'] },
      { emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome'] },
      { emoji: '🤓', keywords: ['nerd', 'glasses', 'geek'] },
      { emoji: '🧐', keywords: ['monocle', 'thinking', 'inspect'] },
      { emoji: '😕', keywords: ['confused', 'unsure', 'puzzled'] },
      { emoji: '😟', keywords: ['worried', 'concerned', 'anxious'] },
      { emoji: '🙁', keywords: ['frown', 'sad', 'disappointed'] },
      { emoji: '😮', keywords: ['open mouth', 'surprised', 'wow'] },
      { emoji: '😯', keywords: ['hushed', 'surprised', 'stunned'] },
      { emoji: '😲', keywords: ['astonished', 'shocked', 'amazed'] },
      { emoji: '😳', keywords: ['flushed', 'embarrassed', 'blushing'] },
      { emoji: '🥺', keywords: ['pleading', 'puppy eyes', 'beg'] },
      { emoji: '😢', keywords: ['crying', 'sad', 'tear'] },
      { emoji: '😭', keywords: ['sobbing', 'loudly crying', 'bawling'] },
      { emoji: '😤', keywords: ['huffing', 'angry', 'frustrated'] },
      { emoji: '😠', keywords: ['angry', 'mad', 'grumpy'] },
      { emoji: '😡', keywords: ['rage', 'furious', 'red face'] },
      { emoji: '🤬', keywords: ['swearing', 'cursing', 'symbols'] },
      { emoji: '👿', keywords: ['devil', 'angry', 'imp'] },
      { emoji: '💀', keywords: ['skull', 'dead', 'death'] },
      { emoji: '☠️', keywords: ['skull crossbones', 'danger', 'toxic'] },
      { emoji: '💩', keywords: ['poop', 'poo', 'funny'] },
      { emoji: '🤡', keywords: ['clown', 'funny', 'circus'] },
      { emoji: '👹', keywords: ['ogre', 'monster', 'japanese'] },
      { emoji: '👻', keywords: ['ghost', 'halloween', 'boo'] },
      { emoji: '👽', keywords: ['alien', 'space', 'ufo', 'extraterrestrial'] },
      { emoji: '🤖', keywords: ['robot', 'bot', 'machine'] },
      { emoji: '😺', keywords: ['cat', 'smile', 'happy'] },
      { emoji: '😻', keywords: ['cat', 'heart eyes', 'love'] },
      { emoji: '🙈', keywords: ['see no evil', 'monkey', 'hide'] },
      { emoji: '🙉', keywords: ['hear no evil', 'monkey'] },
      { emoji: '🙊', keywords: ['speak no evil', 'monkey', 'oops'] },
    ],
  },
  people: {
    label: '👋 People',
    icon: '👋',
    emojis: [
      { emoji: '👋', keywords: ['wave', 'hello', 'goodbye', 'hi'] },
      { emoji: '🤚', keywords: ['raised hand', 'stop', 'back'] },
      { emoji: '🖐️', keywords: ['hand', 'splayed', 'five'] },
      { emoji: '✋', keywords: ['hand', 'stop', 'high five'] },
      { emoji: '🖖', keywords: ['vulcan', 'spock', 'star trek'] },
      { emoji: '👌', keywords: ['ok', 'perfect', 'pinch'] },
      { emoji: '🤌', keywords: ['pinched', 'italian', 'chef kiss'] },
      { emoji: '🤏', keywords: ['pinching', 'small', 'tiny'] },
      { emoji: '✌️', keywords: ['peace', 'victory', 'two'] },
      { emoji: '🤞', keywords: ['crossed fingers', 'luck', 'hope'] },
      { emoji: '🤟', keywords: ['love you', 'rock', 'gesture'] },
      { emoji: '🤘', keywords: ['rock on', 'horns', 'metal'] },
      { emoji: '🤙', keywords: ['call me', 'hang loose', 'shaka'] },
      { emoji: '👈', keywords: ['left', 'point', 'back', 'direction'] },
      { emoji: '👉', keywords: ['right', 'point', 'direction'] },
      { emoji: '👆', keywords: ['up', 'point', 'above'] },
      { emoji: '👇', keywords: ['down', 'point', 'below'] },
      { emoji: '☝️', keywords: ['index finger', 'point up', 'one'] },
      { emoji: '👍', keywords: ['thumbs up', 'like', 'approve', 'yes'] },
      { emoji: '👎', keywords: ['thumbs down', 'dislike', 'no'] },
      { emoji: '✊', keywords: ['fist', 'punch', 'power'] },
      { emoji: '👊', keywords: ['fist bump', 'punch', 'bro'] },
      { emoji: '🤛', keywords: ['left fist', 'bump'] },
      { emoji: '🤜', keywords: ['right fist', 'bump'] },
      { emoji: '👏', keywords: ['clap', 'bravo', 'applause'] },
      { emoji: '🙌', keywords: ['raised hands', 'celebration', 'hooray'] },
      { emoji: '👐', keywords: ['open hands', 'jazz hands'] },
      { emoji: '🤲', keywords: ['palms up', 'prayer', 'receive'] },
      { emoji: '🤝', keywords: ['handshake', 'deal', 'agree', 'partnership'] },
      { emoji: '🙏', keywords: ['pray', 'please', 'thank you', 'hope'] },
      { emoji: '✍️', keywords: ['writing', 'pen', 'compose'] },
      { emoji: '💅', keywords: ['nail polish', 'beauty', 'fabulous'] },
      { emoji: '🤳', keywords: ['selfie', 'phone', 'photo'] },
      { emoji: '💪', keywords: ['muscle', 'strong', 'flex', 'bicep'] },
      { emoji: '🦾', keywords: ['prosthetic arm', 'robot', 'mechanical'] },
      { emoji: '🧠', keywords: ['brain', 'smart', 'think', 'mind'] },
      { emoji: '👀', keywords: ['eyes', 'look', 'see', 'watch'] },
      { emoji: '👁️', keywords: ['eye', 'look', 'see'] },
      { emoji: '👃', keywords: ['nose', 'smell', 'sniff'] },
      { emoji: '👂', keywords: ['ear', 'hear', 'listen'] },
      { emoji: '👄', keywords: ['lips', 'mouth', 'kiss'] },
      { emoji: '👶', keywords: ['baby', 'infant', 'child'] },
      { emoji: '🧒', keywords: ['child', 'kid', 'young'] },
      { emoji: '👧', keywords: ['girl', 'young', 'female'] },
      { emoji: '👦', keywords: ['boy', 'young', 'male'] },
      { emoji: '👩', keywords: ['woman', 'female', 'lady'] },
      { emoji: '👨', keywords: ['man', 'male', 'guy'] },
      { emoji: '🧑', keywords: ['person', 'adult', 'gender neutral'] },
      { emoji: '👴', keywords: ['old man', 'grandpa', 'elderly'] },
      { emoji: '👵', keywords: ['old woman', 'grandma', 'elderly'] },
      { emoji: '🧓', keywords: ['older person', 'elder'] },
      { emoji: '👩‍💻', keywords: ['woman technologist', 'coder', 'developer'] },
      { emoji: '👨‍💻', keywords: ['man technologist', 'coder', 'developer'] },
      { emoji: '👩‍🎨', keywords: ['woman artist', 'painter', 'creative'] },
      { emoji: '👨‍🔬', keywords: ['man scientist', 'lab', 'research'] },
      { emoji: '👩‍🚀', keywords: ['woman astronaut', 'space'] },
      { emoji: '🧑‍🎓', keywords: ['student', 'graduate', 'education'] },
      { emoji: '🧑‍🏫', keywords: ['teacher', 'instructor', 'professor'] },
      { emoji: '🧑‍⚕️', keywords: ['health worker', 'doctor', 'nurse'] },
      { emoji: '🧑‍🍳', keywords: ['cook', 'chef', 'kitchen'] },
      { emoji: '🧑‍🚒', keywords: ['firefighter', 'rescue'] },
      { emoji: '🧑‍✈️', keywords: ['pilot', 'captain', 'aviation'] },
      { emoji: '🧑‍🔧', keywords: ['mechanic', 'plumber', 'fix'] },
    ],
  },
  animals: {
    label: '🐾 Animals',
    icon: '🐾',
    emojis: [
      { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'cute'] },
      { emoji: '🐕', keywords: ['dog', 'pet', 'canine'] },
      { emoji: '🦮', keywords: ['guide dog', 'service', 'assist'] },
      { emoji: '🐩', keywords: ['poodle', 'dog', 'fancy'] },
      { emoji: '🐺', keywords: ['wolf', 'howl', 'wild'] },
      { emoji: '🦊', keywords: ['fox', 'clever', 'red', 'cute'] },
      { emoji: '🦝', keywords: ['raccoon', 'trash panda'] },
      { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'cute'] },
      { emoji: '🐈', keywords: ['cat', 'kitty', 'feline'] },
      { emoji: '🦁', keywords: ['lion', 'king', 'brave', 'courage'] },
      { emoji: '🐯', keywords: ['tiger', 'wild', 'fierce'] },
      { emoji: '🐅', keywords: ['tiger', 'big cat', 'stripes'] },
      { emoji: '🐆', keywords: ['leopard', 'spots', 'wild'] },
      { emoji: '🐴', keywords: ['horse', 'pony', 'ride'] },
      { emoji: '🦄', keywords: ['unicorn', 'magic', 'fantasy', 'rainbow'] },
      { emoji: '🦓', keywords: ['zebra', 'stripes', 'africa'] },
      { emoji: '🐮', keywords: ['cow', 'moo', 'farm'] },
      { emoji: '🐷', keywords: ['pig', 'oink', 'farm', 'cute'] },
      { emoji: '🐽', keywords: ['pig nose', 'snout'] },
      { emoji: '🐏', keywords: ['ram', 'sheep', 'aries'] },
      { emoji: '🐑', keywords: ['sheep', 'lamb', 'wool'] },
      { emoji: '🐐', keywords: ['goat', 'greatest', 'GOAT'] },
      { emoji: '🐪', keywords: ['camel', 'desert', 'hump'] },
      { emoji: '🐫', keywords: ['two hump camel', 'bactrian'] },
      { emoji: '🦙', keywords: ['llama', 'alpaca'] },
      { emoji: '🦒', keywords: ['giraffe', 'tall', 'spots'] },
      { emoji: '🐘', keywords: ['elephant', 'big', 'memory'] },
      { emoji: '', keywords: ['rhinoceros', 'horn'] },
      { emoji: '🦛', keywords: ['hippo', 'hippopotamus'] },
      { emoji: '🐭', keywords: ['mouse', 'rat', 'small', 'cute'] },
      { emoji: '🐹', keywords: ['hamster', 'pet', 'cute'] },
      { emoji: '🐰', keywords: ['rabbit', 'bunny', 'easter', 'cute'] },
      { emoji: '🐻', keywords: ['bear', 'teddy', 'grizzly'] },
      { emoji: '', keywords: ['koala', 'australia', 'cute'] },
      { emoji: '🐼', keywords: ['panda', 'bamboo', 'cute'] },
      { emoji: '🦥', keywords: ['sloth', 'slow', 'lazy'] },
      { emoji: '🦦', keywords: ['otter', 'cute', 'water'] },
      { emoji: '🦨', keywords: ['skunk', 'stink'] },
      { emoji: '🦘', keywords: ['kangaroo', 'australia', 'hop'] },
      { emoji: '🐔', keywords: ['chicken', 'rooster', 'farm'] },
      { emoji: '🐧', keywords: ['penguin', 'cold', 'arctic', 'cute'] },
      { emoji: '🐦', keywords: ['bird', 'fly', 'tweet'] },
      { emoji: '🦅', keywords: ['eagle', 'bird', 'nightjar', 'fly'] },
      { emoji: '🦆', keywords: ['duck', 'quack', 'water'] },
      { emoji: '🦢', keywords: ['swan', 'elegant', 'white'] },
      { emoji: '🦉', keywords: ['owl', 'wise', 'night'] },
      { emoji: '🦩', keywords: ['flamingo', 'pink', 'tropical'] },
      { emoji: '🦜', keywords: ['parrot', 'tropical', 'colorful'] },
      { emoji: '🐸', keywords: ['frog', 'toad', 'ribbit', 'kermit'] },
      { emoji: '🐊', keywords: ['crocodile', 'alligator', 'reptile'] },
      { emoji: '🐢', keywords: ['turtle', 'slow', 'shell'] },
      { emoji: '🦎', keywords: ['lizard', 'reptile', 'gecko'] },
      { emoji: '🐍', keywords: ['snake', 'python', 'slither'] },
      { emoji: '🐉', keywords: ['dragon', 'fire', 'fantasy'] },
      { emoji: '🐲', keywords: ['dragon', 'chinese', 'mythical'] },
      { emoji: '🐳', keywords: ['whale', 'ocean', 'big', 'spouting'] },
      { emoji: '🐬', keywords: ['dolphin', 'ocean', 'smart'] },
      { emoji: '🦈', keywords: ['shark', 'ocean', 'jaws'] },
      { emoji: '🐙', keywords: ['octopus', 'tentacles', 'sea'] },
      { emoji: '🐚', keywords: ['shell', 'beach', 'sea'] },
      { emoji: '🦋', keywords: ['butterfly', 'pretty', 'nature'] },
      { emoji: '🐛', keywords: ['bug', 'insect', 'caterpillar'] },
      { emoji: '🐝', keywords: ['bee', 'honey', 'buzz'] },
      { emoji: '🐞', keywords: ['ladybug', 'luck', 'insect'] },
      { emoji: '🦗', keywords: ['cricket', 'chirp', 'insect'] },
      { emoji: '🕷️', keywords: ['spider', 'web', 'creepy'] },
      { emoji: '🦂', keywords: ['scorpion', 'zodiac', 'sting'] },
      { emoji: '🐾', keywords: ['paw prints', 'pet', 'animal', 'tracks'] },
    ],
  },
  nature: {
    label: '🌸 Nature',
    icon: '🌸',
    emojis: [
      { emoji: '🌸', keywords: ['cherry blossom', 'flower', 'spring'] },
      { emoji: '💮', keywords: ['white flower', 'good', 'score'] },
      { emoji: '🏵️', keywords: ['rosette', 'medal', 'flower'] },
      { emoji: '🌹', keywords: ['rose', 'flower', 'love', 'red'] },
      { emoji: '🥀', keywords: ['wilted flower', 'dead', 'sad'] },
      { emoji: '🌺', keywords: ['hibiscus', 'flower', 'tropical'] },
      { emoji: '🌻', keywords: ['sunflower', 'yellow', 'happy'] },
      { emoji: '🌼', keywords: ['blossom', 'flower', 'daisy'] },
      { emoji: '🌷', keywords: ['tulip', 'flower', 'spring'] },
      { emoji: '🌱', keywords: ['seedling', 'sprout', 'grow', 'new'] },
      { emoji: '🌲', keywords: ['tree', 'evergreen', 'pine'] },
      { emoji: '🌳', keywords: ['tree', 'deciduous', 'nature'] },
      { emoji: '🌴', keywords: ['palm', 'tree', 'tropical', 'beach'] },
      { emoji: '🌵', keywords: ['cactus', 'desert', 'prickly'] },
      { emoji: '🎋', keywords: ['tanabata', 'bamboo', 'wish'] },
      { emoji: '🎍', keywords: ['pine decoration', 'new year'] },
      { emoji: '🍀', keywords: ['clover', 'luck', 'four leaf'] },
      { emoji: '🍁', keywords: ['maple leaf', 'autumn', 'fall'] },
      { emoji: '🍂', keywords: ['fallen leaf', 'autumn'] },
      { emoji: '🍃', keywords: ['leaf', 'wind', 'blowing'] },
      { emoji: '🍄', keywords: ['mushroom', 'forest', 'fungus'] },
      { emoji: '🌰', keywords: ['chestnut', 'nut', 'autumn'] },
      { emoji: '🌈', keywords: ['rainbow', 'colors', 'hope'] },
      { emoji: '☀️', keywords: ['sun', 'sunny', 'bright', 'warm'] },
      { emoji: '🌤️', keywords: ['partly sunny', 'clouds'] },
      { emoji: '⛅', keywords: ['cloudy', 'partly', 'weather'] },
      { emoji: '🌥️', keywords: ['mostly cloudy', 'overcast'] },
      { emoji: '☁️', keywords: ['cloud', 'overcast', 'weather'] },
      { emoji: '🌦️', keywords: ['rain', 'sun', 'shower'] },
      { emoji: '🌧️', keywords: ['rain', 'cloud', 'storm'] },
      { emoji: '⛈️', keywords: ['thunderstorm', 'lightning'] },
      { emoji: '🌩️', keywords: ['lightning', 'cloud', 'storm'] },
      { emoji: '🌪️', keywords: ['tornado', 'twister', 'cyclone'] },
      { emoji: '🌫️', keywords: ['fog', 'mist', 'haze'] },
      { emoji: '🌬️', keywords: ['wind', 'blow', 'breeze'] },
      { emoji: '🌙', keywords: ['moon', 'night', 'crescent'] },
      { emoji: '🌛', keywords: ['moon', 'first quarter', 'face'] },
      { emoji: '🌝', keywords: ['full moon', 'face', 'night'] },
      { emoji: '⭐', keywords: ['star', 'favorite', 'shiny'] },
      { emoji: '🌟', keywords: ['glowing star', 'sparkle', 'shine'] },
      { emoji: '✨', keywords: ['sparkles', 'magic', 'new', 'clean'] },
      { emoji: '💫', keywords: ['dizzy', 'star', 'shooting'] },
      { emoji: '🔥', keywords: ['fire', 'hot', 'flame', 'lit'] },
      { emoji: '💧', keywords: ['water', 'drop', 'rain'] },
      { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'water'] },
      { emoji: '❄️', keywords: ['snowflake', 'cold', 'winter', 'ice'] },
      { emoji: '☃️', keywords: ['snowman', 'winter', 'snow'] },
      { emoji: '⛄', keywords: ['snowman', 'snow', 'winter'] },
      { emoji: '💥', keywords: ['boom', 'explosion', 'collision'] },
    ],
  },
  food: {
    label: '🍔 Food',
    icon: '🍔',
    emojis: [
      { emoji: '🍎', keywords: ['apple', 'red', 'fruit', 'healthy'] },
      { emoji: '🍏', keywords: ['green apple', 'fruit', 'healthy'] },
      { emoji: '🍐', keywords: ['pear', 'fruit', 'green'] },
      { emoji: '🍊', keywords: ['orange', 'citrus', 'fruit'] },
      { emoji: '🍋', keywords: ['lemon', 'yellow', 'sour'] },
      { emoji: '🍌', keywords: ['banana', 'fruit', 'yellow'] },
      { emoji: '🍉', keywords: ['watermelon', 'summer', 'fruit'] },
      { emoji: '🍇', keywords: ['grapes', 'purple', 'fruit'] },
      { emoji: '🍓', keywords: ['strawberry', 'red', 'berry'] },
      { emoji: '🍈', keywords: ['melon', 'cantaloupe', 'fruit'] },
      { emoji: '🍒', keywords: ['cherries', 'red', 'fruit'] },
      { emoji: '🍑', keywords: ['peach', 'fruit', 'pink'] },
      { emoji: '🥭', keywords: ['mango', 'tropical', 'fruit'] },
      { emoji: '🍍', keywords: ['pineapple', 'tropical', 'fruit'] },
      { emoji: '🥥', keywords: ['coconut', 'tropical', 'palm'] },
      { emoji: '🥝', keywords: ['kiwi', 'fruit', 'green'] },
      { emoji: '🥑', keywords: ['avocado', 'guacamole', 'healthy'] },
      { emoji: '🍆', keywords: ['eggplant', 'aubergine', 'purple'] },
      { emoji: '🥔', keywords: ['potato', 'spud', 'vegetable'] },
      { emoji: '🥕', keywords: ['carrot', 'orange', 'vegetable'] },
      { emoji: '🌽', keywords: ['corn', 'maize', 'vegetable'] },
      { emoji: '🌶️', keywords: ['pepper', 'hot', 'spicy', 'chili'] },
      { emoji: '', keywords: ['broccoli', 'vegetable', 'healthy'] },
      { emoji: '🧅', keywords: ['onion', 'vegetable', 'cry'] },
      { emoji: '🧄', keywords: ['garlic', 'cooking', 'flavor'] },
      { emoji: '🥐', keywords: ['croissant', 'french', 'pastry'] },
      { emoji: '🍞', keywords: ['bread', 'loaf', 'toast'] },
      { emoji: '🥖', keywords: ['baguette', 'french bread'] },
      { emoji: '🥨', keywords: ['pretzel', 'snack', 'twisted'] },
      { emoji: '🧀', keywords: ['cheese', 'dairy', 'cheddar'] },
      { emoji: '🥚', keywords: ['egg', 'breakfast', 'chicken'] },
      { emoji: '🍳', keywords: ['cooking', 'egg', 'frying pan'] },
      { emoji: '🧈', keywords: ['butter', 'dairy', 'spread'] },
      { emoji: '🥞', keywords: ['pancakes', 'breakfast', 'stack'] },
      { emoji: '🧇', keywords: ['waffle', 'breakfast', 'grid'] },
      { emoji: '🥓', keywords: ['bacon', 'meat', 'breakfast'] },
      { emoji: '🍔', keywords: ['hamburger', 'burger', 'food'] },
      { emoji: '🍟', keywords: ['french fries', 'chips', 'potato'] },
      { emoji: '🍕', keywords: ['pizza', 'food', 'italian'] },
      { emoji: '🌭', keywords: ['hot dog', 'sausage', 'food'] },
      { emoji: '🥪', keywords: ['sandwich', 'lunch', 'bread'] },
      { emoji: '🌮', keywords: ['taco', 'mexican', 'food'] },
      { emoji: '🌯', keywords: ['burrito', 'wrap', 'mexican'] },
      { emoji: '', keywords: ['pita', 'falafel', 'kebab'] },
      { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian'] },
      { emoji: '🍜', keywords: ['ramen', 'noodles', 'soup'] },
      { emoji: '🍲', keywords: ['stew', 'pot', 'food'] },
      { emoji: '🍛', keywords: ['curry', 'rice', 'indian'] },
      { emoji: '🍣', keywords: ['sushi', 'japanese', 'food'] },
      { emoji: '🍱', keywords: ['bento', 'japanese', 'lunch box'] },
      { emoji: '🥟', keywords: ['dumpling', 'chinese', 'gyoza'] },
      { emoji: '🍩', keywords: ['donut', 'doughnut', 'sweet'] },
      { emoji: '🍰', keywords: ['cake', 'dessert', 'birthday'] },
      { emoji: '🎂', keywords: ['birthday cake', 'party', 'celebration'] },
      { emoji: '🧁', keywords: ['cupcake', 'sweet', 'dessert'] },
      { emoji: '🍫', keywords: ['chocolate', 'candy', 'sweet'] },
      { emoji: '🍬', keywords: ['candy', 'sweet', 'sugar'] },
      { emoji: '🍭', keywords: ['lollipop', 'candy', 'sweet'] },
      { emoji: '🍦', keywords: ['ice cream', 'cone', 'summer'] },
      { emoji: '🍧', keywords: ['shaved ice', 'dessert', 'cold'] },
      { emoji: '🍨', keywords: ['ice cream', 'sundae', 'dessert'] },
      { emoji: '🍪', keywords: ['cookie', 'biscuit', 'sweet'] },
      { emoji: '🍿', keywords: ['popcorn', 'movie', 'snack'] },
      { emoji: '☕', keywords: ['coffee', 'tea', 'hot', 'cafe'] },
      { emoji: '🍵', keywords: ['tea', 'green tea', 'matcha'] },
      { emoji: '', keywords: ['drink', 'soda', 'cup'] },
      { emoji: '🧃', keywords: ['juice box', 'drink', 'kids'] },
      { emoji: '🍺', keywords: ['beer', 'drink', 'cheers'] },
      { emoji: '🍻', keywords: ['clinking beers', 'cheers', 'toast'] },
      { emoji: '🥂', keywords: ['champagne', 'toast', 'celebrate'] },
      { emoji: '🍷', keywords: ['wine', 'red', 'glass'] },
      { emoji: '🍸', keywords: ['cocktail', 'martini', 'drink'] },
      { emoji: '🍹', keywords: ['tropical drink', 'cocktail', 'vacation'] },
      { emoji: '🧊', keywords: ['ice', 'cube', 'cold'] },
    ],
  },
  activities: {
    label: '🎮 Activities',
    icon: '🎮',
    emojis: [
      { emoji: '⚽', keywords: ['soccer', 'football', 'ball', 'sport'] },
      { emoji: '🏀', keywords: ['basketball', 'sport', 'ball'] },
      { emoji: '🏈', keywords: ['football', 'american', 'sport'] },
      { emoji: '⚾', keywords: ['baseball', 'sport', 'ball'] },
      { emoji: '🥎', keywords: ['softball', 'sport', 'ball'] },
      { emoji: '🎾', keywords: ['tennis', 'sport', 'ball'] },
      { emoji: '🏐', keywords: ['volleyball', 'sport', 'ball'] },
      { emoji: '🏉', keywords: ['rugby', 'sport', 'ball'] },
      { emoji: '🥏', keywords: ['frisbee', 'disc', 'throw'] },
      { emoji: '🎱', keywords: ['pool', 'billiards', 'eight ball'] },
      { emoji: '🏓', keywords: ['table tennis', 'ping pong'] },
      { emoji: '🏸', keywords: ['badminton', 'shuttlecock'] },
      { emoji: '🏒', keywords: ['ice hockey', 'sport'] },
      { emoji: '🥊', keywords: ['boxing', 'glove', 'fight'] },
      { emoji: '🥋', keywords: ['martial arts', 'karate', 'judo'] },
      { emoji: '🎿', keywords: ['skiing', 'snow', 'winter'] },
      { emoji: '⛷️', keywords: ['skier', 'skiing', 'snow'] },
      { emoji: '🏂', keywords: ['snowboard', 'winter', 'sport'] },
      { emoji: '🏋️', keywords: ['weightlifting', 'gym', 'strong'] },
      { emoji: '🤸', keywords: ['gymnastics', 'cartwheel', 'flexible'] },
      { emoji: '🏊', keywords: ['swimming', 'pool', 'water'] },
      { emoji: '🚴', keywords: ['cycling', 'bike', 'bicycle'] },
      { emoji: '🧗', keywords: ['climbing', 'rock', 'sport'] },
      { emoji: '🤺', keywords: ['fencing', 'sword', 'sport'] },
      { emoji: '🏇', keywords: ['horse racing', 'jockey'] },
      { emoji: '🎮', keywords: ['game', 'controller', 'video game', 'gaming'] },
      { emoji: '🕹️', keywords: ['joystick', 'arcade', 'game'] },
      { emoji: '🎲', keywords: ['dice', 'game', 'random', 'luck'] },
      { emoji: '♟️', keywords: ['chess', 'pawn', 'strategy'] },
      { emoji: '🧩', keywords: ['puzzle', 'jigsaw', 'piece'] },
      { emoji: '🎯', keywords: ['target', 'dart', 'goal', 'bullseye'] },
      { emoji: '🏆', keywords: ['trophy', 'winner', 'champion', 'award'] },
      { emoji: '🥇', keywords: ['gold', 'medal', 'first', 'winner'] },
      { emoji: '🥈', keywords: ['silver', 'medal', 'second'] },
      { emoji: '🥉', keywords: ['bronze', 'medal', 'third'] },
      { emoji: '🏅', keywords: ['medal', 'sports', 'achievement'] },
      { emoji: '🎖️', keywords: ['military medal', 'honor', 'award'] },
      { emoji: '🎪', keywords: ['circus', 'tent', 'carnival'] },
      { emoji: '🎨', keywords: ['art', 'palette', 'paint', 'creative'] },
      { emoji: '🎭', keywords: ['theater', 'drama', 'masks', 'acting'] },
      { emoji: '🎬', keywords: ['movie', 'film', 'clapper', 'cinema'] },
      { emoji: '🎵', keywords: ['music', 'note', 'song', 'melody'] },
      { emoji: '🎶', keywords: ['music notes', 'song', 'melody'] },
      { emoji: '🎤', keywords: ['microphone', 'sing', 'karaoke'] },
      { emoji: '🎧', keywords: ['headphones', 'music', 'listen', 'audio'] },
      { emoji: '🎷', keywords: ['saxophone', 'jazz', 'music'] },
      { emoji: '🎸', keywords: ['guitar', 'rock', 'music', 'instrument'] },
      { emoji: '🎹', keywords: ['piano', 'keyboard', 'music', 'keys'] },
      { emoji: '', keywords: ['drum', 'beat', 'percussion'] },
      { emoji: '🎺', keywords: ['trumpet', 'brass', 'music'] },
      { emoji: '🎻', keywords: ['violin', 'fiddle', 'strings'] },
      { emoji: '🎰', keywords: ['slot machine', 'casino', 'gamble'] },
      { emoji: '🎳', keywords: ['bowling', 'sport', 'pins'] },
    ],
  },
  travel: {
    label: '✈️ Travel',
    icon: '✈️',
    emojis: [
      { emoji: '🚗', keywords: ['car', 'auto', 'drive', 'vehicle'] },
      { emoji: '🚕', keywords: ['taxi', 'cab', 'ride'] },
      { emoji: '🚙', keywords: ['suv', 'car', 'sport utility'] },
      { emoji: '🚌', keywords: ['bus', 'transit', 'public'] },
      { emoji: '🚎', keywords: ['trolleybus', 'transit'] },
      { emoji: '🏎️', keywords: ['race car', 'formula', 'fast'] },
      { emoji: '🚓', keywords: ['police car', 'cop', 'law'] },
      { emoji: '🚑', keywords: ['ambulance', 'emergency', 'medical'] },
      { emoji: '🚒', keywords: ['fire engine', 'fire truck'] },
      { emoji: '🚐', keywords: ['minibus', 'van', 'shuttle'] },
      { emoji: '', keywords: ['delivery truck', 'moving'] },
      { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycle'] },
      { emoji: '🛵', keywords: ['scooter', 'motor', 'vespa'] },
      { emoji: '🏍️', keywords: ['motorcycle', 'bike', 'ride'] },
      { emoji: '🛺', keywords: ['auto rickshaw', 'tuk tuk'] },
      { emoji: '🚀', keywords: ['rocket', 'space', 'launch', 'fast'] },
      { emoji: '✈️', keywords: ['airplane', 'plane', 'fly', 'travel'] },
      { emoji: '🛩️', keywords: ['small airplane', 'private', 'plane'] },
      { emoji: '🚁', keywords: ['helicopter', 'chopper', 'fly'] },
      { emoji: '🛸', keywords: ['flying saucer', 'ufo', 'alien'] },
      { emoji: '🚂', keywords: ['train', 'locomotive', 'rail'] },
      { emoji: '🚄', keywords: ['high speed train', 'bullet'] },
      { emoji: '🚢', keywords: ['ship', 'boat', 'cruise', 'sail'] },
      { emoji: '⛵', keywords: ['sailboat', 'sail', 'wind'] },
      { emoji: '🛥️', keywords: ['motor boat', 'speed boat'] },
      { emoji: '🚤', keywords: ['speedboat', 'fast', 'water'] },
      { emoji: '⛽', keywords: ['fuel', 'gas', 'pump', 'station'] },
      { emoji: '🏠', keywords: ['house', 'home', 'building'] },
      { emoji: '🏡', keywords: ['house garden', 'home', 'yard'] },
      { emoji: '🏢', keywords: ['office', 'building', 'work'] },
      { emoji: '🏣', keywords: ['japanese post office'] },
      { emoji: '🏥', keywords: ['hospital', 'medical', 'health'] },
      { emoji: '🏦', keywords: ['bank', 'money', 'finance'] },
      { emoji: '🏨', keywords: ['hotel', 'accommodation', 'travel'] },
      { emoji: '🏩', keywords: ['love hotel', 'heart'] },
      { emoji: '🏪', keywords: ['convenience store', 'shop'] },
      { emoji: '🏫', keywords: ['school', 'education', 'building'] },
      { emoji: '🏬', keywords: ['department store', 'mall'] },
      { emoji: '🏭', keywords: ['factory', 'industrial', 'manufacturing'] },
      { emoji: '🏗️', keywords: ['construction', 'building', 'crane'] },
      { emoji: '⛪', keywords: ['church', 'religion', 'building'] },
      { emoji: '🕌', keywords: ['mosque', 'islam', 'religion'] },
      { emoji: '🛕', keywords: ['hindu temple', 'religion'] },
      { emoji: '🗽', keywords: ['statue of liberty', 'new york', 'landmark'] },
      { emoji: '🗼', keywords: ['tower', 'tokyo', 'landmark'] },
      { emoji: '🏰', keywords: ['castle', 'fairy tale', 'medieval'] },
      { emoji: '🗻', keywords: ['mount fuji', 'japan', 'mountain'] },
      { emoji: '🏔️', keywords: ['mountain', 'snow', 'peak'] },
      { emoji: '⛰️', keywords: ['mountain', 'hill', 'hike'] },
      { emoji: '🌋', keywords: ['volcano', 'eruption', 'lava'] },
      { emoji: '🏖️', keywords: ['beach', 'vacation', 'umbrella'] },
      { emoji: '🏜️', keywords: ['desert', 'sand', 'dry'] },
      { emoji: '🏕️', keywords: ['camping', 'tent', 'outdoors'] },
      { emoji: '🌍', keywords: ['globe', 'earth', 'world', 'europe'] },
      { emoji: '🌎', keywords: ['globe', 'earth', 'americas'] },
      { emoji: '🌏', keywords: ['globe', 'earth', 'asia', 'australia'] },
      { emoji: '🗺️', keywords: ['map', 'world', 'geography'] },
      { emoji: '🧭', keywords: ['compass', 'direction', 'navigation'] },
      { emoji: '🗿', keywords: ['moai', 'easter island', 'stone'] },
    ],
  },
  objects: {
    label: '💡 Objects',
    icon: '💡',
    emojis: [
      { emoji: '💡', keywords: ['idea', 'light', 'bulb', 'bright'] },
      { emoji: '🔮', keywords: ['crystal ball', 'magic', 'fortune'] },
      { emoji: '💎', keywords: ['diamond', 'gem', 'jewel', 'precious'] },
      { emoji: '🔑', keywords: ['key', 'lock', 'access', 'secure'] },
      { emoji: '🗝️', keywords: ['old key', 'antique', 'lock'] },
      { emoji: '🔒', keywords: ['lock', 'secure', 'private', 'closed'] },
      { emoji: '🔓', keywords: ['unlock', 'open', 'access'] },
      { emoji: '🛡️', keywords: ['shield', 'protect', 'defense', 'security'] },
      { emoji: '⚔️', keywords: ['swords', 'crossed', 'battle'] },
      { emoji: '📱', keywords: ['phone', 'mobile', 'cell', 'smartphone'] },
      { emoji: '💻', keywords: ['laptop', 'computer', 'pc', 'tech'] },
      { emoji: '🖥️', keywords: ['desktop', 'monitor', 'screen', 'computer'] },
      { emoji: '🖨️', keywords: ['printer', 'print', 'paper'] },
      { emoji: '⌨️', keywords: ['keyboard', 'type', 'input'] },
      { emoji: '🖱️', keywords: ['mouse', 'computer', 'click'] },
      { emoji: '💾', keywords: ['floppy', 'save', 'disk', 'storage'] },
      { emoji: '💿', keywords: ['cd', 'disc', 'optical'] },
      { emoji: '📀', keywords: ['dvd', 'disc', 'movie'] },
      { emoji: '📷', keywords: ['camera', 'photo', 'picture'] },
      { emoji: '📹', keywords: ['video camera', 'record', 'film'] },
      { emoji: '🎥', keywords: ['movie camera', 'film', 'cinema'] },
      { emoji: '📺', keywords: ['television', 'tv', 'screen'] },
      { emoji: '📻', keywords: ['radio', 'broadcast', 'music'] },
      { emoji: '📡', keywords: ['satellite', 'antenna', 'signal'] },
      { emoji: '🔌', keywords: ['plug', 'electric', 'power', 'connect'] },
      { emoji: '🔋', keywords: ['battery', 'power', 'energy'] },
      { emoji: '🔦', keywords: ['flashlight', 'torch', 'light'] },
      { emoji: '🕯️', keywords: ['candle', 'light', 'flame'] },
      { emoji: '📚', keywords: ['books', 'library', 'read', 'study'] },
      { emoji: '📖', keywords: ['book', 'open', 'read'] },
      { emoji: '📝', keywords: ['memo', 'note', 'write', 'pencil'] },
      { emoji: '📄', keywords: ['page', 'document', 'paper'] },
      { emoji: '📃', keywords: ['page', 'curl', 'document'] },
      { emoji: '📋', keywords: ['clipboard', 'list', 'task'] },
      { emoji: '📁', keywords: ['folder', 'file', 'directory'] },
      { emoji: '📂', keywords: ['folder', 'open', 'file'] },
      { emoji: '🗃️', keywords: ['card box', 'file', 'archive', 'storage'] },
      { emoji: '🗂️', keywords: ['dividers', 'tabs', 'organize', 'index'] },
      { emoji: '📊', keywords: ['chart', 'graph', 'bar', 'data', 'stats'] },
      { emoji: '📈', keywords: ['chart', 'growth', 'up', 'trend'] },
      { emoji: '📉', keywords: ['chart', 'down', 'decline', 'trend'] },
      { emoji: '📅', keywords: ['calendar', 'date', 'schedule'] },
      { emoji: '📆', keywords: ['tear-off calendar', 'date'] },
      { emoji: '🗓️', keywords: ['spiral calendar', 'schedule'] },
      { emoji: '📌', keywords: ['pin', 'pushpin', 'thumbtack'] },
      { emoji: '📍', keywords: ['pin', 'location', 'map'] },
      { emoji: '📎', keywords: ['paperclip', 'clip', 'attach'] },
      { emoji: '🖇️', keywords: ['linked paperclips', 'attach'] },
      { emoji: '📏', keywords: ['ruler', 'measure', 'straight'] },
      { emoji: '📐', keywords: ['triangle ruler', 'set square'] },
      { emoji: '✏️', keywords: ['pencil', 'write', 'draw', 'edit'] },
      { emoji: '🖊️', keywords: ['pen', 'write', 'ballpoint'] },
      { emoji: '🖋️', keywords: ['fountain pen', 'write', 'ink'] },
      { emoji: '✒️', keywords: ['black nib', 'pen', 'write'] },
      { emoji: '🔍', keywords: ['search', 'magnify', 'look', 'find'] },
      { emoji: '🔎', keywords: ['magnifying glass', 'inspect'] },
      { emoji: '💼', keywords: ['briefcase', 'work', 'business', 'job'] },
      { emoji: '🎁', keywords: ['gift', 'present', 'birthday', 'box'] },
      { emoji: '🎀', keywords: ['ribbon', 'bow', 'decoration'] },
      { emoji: '⚙️', keywords: ['gear', 'settings', 'config', 'cog'] },
      { emoji: '🔧', keywords: ['wrench', 'tool', 'fix', 'repair'] },
      { emoji: '🔨', keywords: ['hammer', 'build', 'tool'] },
      { emoji: '🛠️', keywords: ['tools', 'hammer', 'wrench', 'build'] },
      { emoji: '⛏️', keywords: ['pick', 'mine', 'dig'] },
      { emoji: '', keywords: ['magnet', 'attract', 'pull'] },
      { emoji: '🧪', keywords: ['test tube', 'science', 'lab'] },
      { emoji: '🧫', keywords: ['petri dish', 'science', 'lab'] },
      { emoji: '🔬', keywords: ['microscope', 'science', 'lab', 'tiny'] },
      { emoji: '🔭', keywords: ['telescope', 'astronomy', 'space'] },
      { emoji: '📦', keywords: ['package', 'box', 'delivery', 'ship'] },
      { emoji: '🏷️', keywords: ['tag', 'label', 'price'] },
      { emoji: '🧮', keywords: ['abacus', 'count', 'math'] },
    ],
  },
  symbols: {
    label: '🔣 Symbols',
    icon: '🔣',
    emojis: [
      { emoji: '❤️', keywords: ['heart', 'love', 'red'] },
      { emoji: '🧡', keywords: ['heart', 'orange', 'love'] },
      { emoji: '💛', keywords: ['heart', 'yellow', 'love'] },
      { emoji: '💚', keywords: ['heart', 'green', 'love'] },
      { emoji: '💙', keywords: ['heart', 'blue', 'love'] },
      { emoji: '💜', keywords: ['heart', 'purple', 'love'] },
      { emoji: '🖤', keywords: ['heart', 'black', 'dark'] },
      { emoji: '🤍', keywords: ['heart', 'white', 'pure'] },
      { emoji: '🤎', keywords: ['heart', 'brown', 'love'] },
      { emoji: '💔', keywords: ['broken heart', 'sad', 'breakup'] },
      { emoji: '💕', keywords: ['two hearts', 'love', 'affection'] },
      { emoji: '💞', keywords: ['revolving hearts', 'love'] },
      { emoji: '💓', keywords: ['beating heart', 'love', 'pulse'] },
      { emoji: '💗', keywords: ['growing heart', 'love', 'bigger'] },
      { emoji: '💖', keywords: ['sparkling heart', 'love', 'shine'] },
      { emoji: '💘', keywords: ['heart arrow', 'cupid', 'love'] },
      { emoji: '💝', keywords: ['heart ribbon', 'gift', 'valentine'] },
      { emoji: '💟', keywords: ['heart decoration', 'ornament'] },
      { emoji: '💯', keywords: ['hundred', 'perfect', 'score', '100'] },
      { emoji: '💢', keywords: ['anger', 'vein', 'frustration'] },
      { emoji: '💬', keywords: ['speech bubble', 'talk', 'chat', 'comment'] },
      { emoji: '', keywords: ['thought bubble', 'think', 'cloud'] },
      { emoji: '💤', keywords: ['zzz', 'sleep', 'snore'] },
      { emoji: '✅', keywords: ['check', 'done', 'complete', 'yes'] },
      { emoji: '❌', keywords: ['cross', 'no', 'wrong', 'delete'] },
      { emoji: '❓', keywords: ['question', 'help', 'what'] },
      { emoji: '❗', keywords: ['exclamation', 'important', 'alert'] },
      { emoji: '‼️', keywords: ['double exclamation', 'urgent'] },
      { emoji: '⁉️', keywords: ['exclamation question', 'interrobang'] },
      { emoji: '⚠️', keywords: ['warning', 'caution', 'alert'] },
      { emoji: '🚫', keywords: ['prohibited', 'no entry', 'forbidden'] },
      { emoji: '⛔', keywords: ['no entry', 'stop', 'forbidden'] },
      { emoji: '🔴', keywords: ['red circle', 'dot', 'stop'] },
      { emoji: '🟠', keywords: ['orange circle', 'dot'] },
      { emoji: '🟡', keywords: ['yellow circle', 'dot'] },
      { emoji: '🟢', keywords: ['green circle', 'dot', 'go'] },
      { emoji: '🔵', keywords: ['blue circle', 'dot'] },
      { emoji: '🟣', keywords: ['purple circle', 'dot'] },
      { emoji: '🟤', keywords: ['brown circle', 'dot'] },
      { emoji: '⚫', keywords: ['black circle', 'dot'] },
      { emoji: '⚪', keywords: ['white circle', 'dot'] },
      { emoji: '🟥', keywords: ['red square', 'block'] },
      { emoji: '🟧', keywords: ['orange square', 'block'] },
      { emoji: '🟨', keywords: ['yellow square', 'block'] },
      { emoji: '🟩', keywords: ['green square', 'block'] },
      { emoji: '🟦', keywords: ['blue square', 'block'] },
      { emoji: '🟪', keywords: ['purple square', 'block'] },
      { emoji: '⬆️', keywords: ['up', 'arrow', 'north'] },
      { emoji: '⬇️', keywords: ['down', 'arrow', 'south'] },
      { emoji: '➡️', keywords: ['right', 'arrow', 'east', 'next'] },
      { emoji: '⬅️', keywords: ['left', 'arrow', 'west', 'back'] },
      { emoji: '↗️', keywords: ['up right', 'arrow', 'northeast'] },
      { emoji: '↘️', keywords: ['down right', 'arrow', 'southeast'] },
      { emoji: '↙️', keywords: ['down left', 'arrow', 'southwest'] },
      { emoji: '↖️', keywords: ['up left', 'arrow', 'northwest'] },
      { emoji: '🔄', keywords: ['counterclockwise', 'refresh', 'reload'] },
      { emoji: '🔃', keywords: ['clockwise', 'arrows', 'cycle'] },
      { emoji: '♻️', keywords: ['recycle', 'environment', 'green'] },
      { emoji: '🔗', keywords: ['link', 'chain', 'connect', 'url'] },
      { emoji: '📛', keywords: ['name badge', 'tag'] },
      { emoji: '🔰', keywords: ['beginner', 'japanese', 'new driver'] },
      { emoji: '⭕', keywords: ['circle', 'ring', 'correct'] },
      { emoji: '✳️', keywords: ['asterisk', 'sparkle'] },
      { emoji: '❇️', keywords: ['sparkle', 'green', 'new'] },
      { emoji: '©️', keywords: ['copyright', 'ip'] },
      { emoji: '®️', keywords: ['registered', 'trademark'] },
      { emoji: '™️', keywords: ['trademark', 'brand'] },
      { emoji: '🔢', keywords: ['numbers', '1234', 'input'] },
      { emoji: '🔤', keywords: ['abc', 'alphabet', 'letters'] },
      { emoji: '#️⃣', keywords: ['hash', 'hashtag', 'number sign'] },
      { emoji: '*️⃣', keywords: ['asterisk', 'star', 'key'] },
      { emoji: '🔣', keywords: ['symbols', 'input'] },
      { emoji: '🔠', keywords: ['uppercase', 'ABCD', 'letters'] },
      { emoji: '🆕', keywords: ['new', 'fresh', 'badge'] },
      { emoji: '🆓', keywords: ['free', 'gratis', 'badge'] },
      { emoji: '🆒', keywords: ['cool', 'nice', 'badge'] },
      { emoji: '🆗', keywords: ['ok', 'okay', 'badge'] },
      { emoji: '🆘', keywords: ['sos', 'help', 'emergency'] },
      { emoji: '🏧', keywords: ['atm', 'bank', 'money'] },
      { emoji: '♾️', keywords: ['infinity', 'forever', 'loop'] },
      { emoji: '⚡', keywords: ['lightning', 'zap', 'electric', 'fast'] },
    ],
  },
  flags: {
    label: '🏁 Flags',
    icon: '🏁',
    emojis: [
      { emoji: '🏁', keywords: ['checkered', 'finish', 'race', 'flag'] },
      { emoji: '🚩', keywords: ['red flag', 'warning', 'triangular'] },
      { emoji: '🎌', keywords: ['crossed flags', 'japan', 'celebration'] },
      { emoji: '🏴', keywords: ['black flag', 'pirate'] },
      { emoji: '🏳️', keywords: ['white flag', 'surrender', 'peace'] },
      { emoji: '🏳️‍🌈', keywords: ['rainbow', 'pride', 'lgbtq'] },
      { emoji: '‍☠️', keywords: ['pirate flag', 'jolly roger'] },
      { emoji: '🇺🇸', keywords: ['usa', 'america', 'united states'] },
      { emoji: '🇬🇧', keywords: ['uk', 'britain', 'england'] },
      { emoji: '🇫🇷', keywords: ['france', 'french'] },
      { emoji: '🇩🇪', keywords: ['germany', 'german'] },
      { emoji: '🇮🇹', keywords: ['italy', 'italian'] },
      { emoji: '🇪🇸', keywords: ['spain', 'spanish'] },
      { emoji: '🇵🇹', keywords: ['portugal', 'portuguese'] },
      { emoji: '🇳🇱', keywords: ['netherlands', 'dutch', 'holland'] },
      { emoji: '🇧🇪', keywords: ['belgium', 'belgian'] },
      { emoji: '🇨🇭', keywords: ['switzerland', 'swiss'] },
      { emoji: '🇦🇹', keywords: ['austria', 'austrian'] },
      { emoji: '🇸🇪', keywords: ['sweden', 'swedish'] },
      { emoji: '🇳🇴', keywords: ['norway', 'norwegian'] },
      { emoji: '🇩🇰', keywords: ['denmark', 'danish'] },
      { emoji: '🇫🇮', keywords: ['finland', 'finnish'] },
      { emoji: '🇮🇪', keywords: ['ireland', 'irish'] },
      { emoji: '🇵🇱', keywords: ['poland', 'polish'] },
      { emoji: '🇬🇷', keywords: ['greece', 'greek'] },
      { emoji: '🇹🇷', keywords: ['turkey', 'turkish'] },
      { emoji: '🇷🇺', keywords: ['russia', 'russian'] },
      { emoji: '🇺🇦', keywords: ['ukraine', 'ukrainian'] },
      { emoji: '🇯🇵', keywords: ['japan', 'japanese'] },
      { emoji: '🇰🇷', keywords: ['korea', 'south korea', 'korean'] },
      { emoji: '🇨🇳', keywords: ['china', 'chinese'] },
      { emoji: '🇹🇼', keywords: ['taiwan', 'taiwanese'] },
      { emoji: '🇮🇳', keywords: ['india', 'indian'] },
      { emoji: '🇵🇰', keywords: ['pakistan', 'pakistani'] },
      { emoji: '🇧🇩', keywords: ['bangladesh', 'bangladeshi'] },
      { emoji: '🇹🇭', keywords: ['thailand', 'thai'] },
      { emoji: '🇻🇳', keywords: ['vietnam', 'vietnamese'] },
      { emoji: '🇮🇩', keywords: ['indonesia', 'indonesian'] },
      { emoji: '🇵🇭', keywords: ['philippines', 'filipino'] },
      { emoji: '🇲🇾', keywords: ['malaysia', 'malaysian'] },
      { emoji: '🇸🇬', keywords: ['singapore', 'singaporean'] },
      { emoji: '🇦🇺', keywords: ['australia', 'australian'] },
      { emoji: '🇳🇿', keywords: ['new zealand', 'kiwi'] },
      { emoji: '🇧🇷', keywords: ['brazil', 'brazilian'] },
      { emoji: '🇦🇷', keywords: ['argentina', 'argentinian'] },
      { emoji: '🇲🇽', keywords: ['mexico', 'mexican'] },
      { emoji: '🇨🇴', keywords: ['colombia', 'colombian'] },
      { emoji: '🇨🇱', keywords: ['chile', 'chilean'] },
      { emoji: '🇵🇪', keywords: ['peru', 'peruvian'] },
      { emoji: '🇨🇦', keywords: ['canada', 'canadian'] },
      { emoji: '🇿🇦', keywords: ['south africa', 'south african'] },
      { emoji: '🇳🇬', keywords: ['nigeria', 'nigerian'] },
      { emoji: '🇪🇬', keywords: ['egypt', 'egyptian'] },
      { emoji: '🇰🇪', keywords: ['kenya', 'kenyan'] },
      { emoji: '🇪🇹', keywords: ['ethiopia', 'ethiopian'] },
      { emoji: '🇬🇭', keywords: ['ghana', 'ghanaian'] },
      { emoji: '🇲🇦', keywords: ['morocco', 'moroccan'] },
      { emoji: '🇸🇦', keywords: ['saudi arabia', 'saudi'] },
      { emoji: '🇦🇪', keywords: ['uae', 'emirates', 'dubai'] },
      { emoji: '🇮🇱', keywords: ['israel', 'israeli'] },
      { emoji: '🇮🇶', keywords: ['iraq', 'iraqi'] },
      { emoji: '🇮🇷', keywords: ['iran', 'iranian'] },
    ],
  },
};

// ---------------------------------------------------------------------------
// EMOJI CATEGORIES — ordered array for iteration
// ---------------------------------------------------------------------------
export const EMOJI_CATEGORIES = Object.keys(EMOJI_DATA);

// ---------------------------------------------------------------------------
// ALL_ICONS — flat array of every emoji string
// ---------------------------------------------------------------------------
export const ALL_ICONS = EMOJI_CATEGORIES.flatMap((cat) =>
  EMOJI_DATA[cat].emojis.map((e) => e.emoji)
);

// ---------------------------------------------------------------------------
// Popular emojis for the mini-strip when there are no recents
// ---------------------------------------------------------------------------
export const POPULAR_EMOJIS = [
  '📁', '📝', '🚀', '💡', '⭐', '🔥', '✨', '🎯', '💎', '📊',
  '🎨', '🏆', '📚', '⚙️', '💼', '🌟',
];

// ---------------------------------------------------------------------------
// COLOR PALETTE — 30 colors spanning the full spectrum
// ---------------------------------------------------------------------------
export const PRESET_COLORS = [
  { hex: '#ef4444', name: 'Red' },
  { hex: '#f87171', name: 'Red Light' },
  { hex: '#f97316', name: 'Orange' },
  { hex: '#f59e0b', name: 'Amber' },
  { hex: '#eab308', name: 'Yellow' },
  { hex: '#fde047', name: 'Yellow Light' },
  { hex: '#84cc16', name: 'Lime' },
  { hex: '#22c55e', name: 'Green' },
  { hex: '#10b981', name: 'Emerald' },
  { hex: '#14b8a6', name: 'Teal' },
  { hex: '#06b6d4', name: 'Cyan' },
  { hex: '#0ea5e9', name: 'Sky' },
  { hex: '#3b82f6', name: 'Blue' },
  { hex: '#60a5fa', name: 'Blue Light' },
  { hex: '#6366f1', name: 'Indigo' },
  { hex: '#8b5cf6', name: 'Violet' },
  { hex: '#a855f7', name: 'Purple' },
  { hex: '#d946ef', name: 'Fuchsia' },
  { hex: '#ec4899', name: 'Pink' },
  { hex: '#f43f5e', name: 'Rose' },
  { hex: '#78716c', name: 'Warm Gray' },
  { hex: '#6b7280', name: 'Cool Gray' },
  { hex: '#64748b', name: 'Slate' },
  { hex: '#1e3a5f', name: 'Dark Blue' },
  { hex: '#92400e', name: 'Brown' },
  { hex: '#ff6f61', name: 'Coral' },
  { hex: '#6ee7b7', name: 'Mint' },
  { hex: '#c4b5fd', name: 'Lavender' },
  { hex: '#ffffff', name: 'White' },
  { hex: '#111111', name: 'Black' },
];

export const PRESET_COLOR_HEXES = PRESET_COLORS.map((c) => c.hex);

// ---------------------------------------------------------------------------
// Backward-compat alias for the old PRESET_ICONS export
// ---------------------------------------------------------------------------
export const PRESET_ICONS = {
  folders: ['📁', '📂', '🗂️', '📑', '📋', '📚', '📖', '🗃️'],
  documents: ['📄', '📝', '📃', '📜', '📰', '🗒️', '📓', '📔'],
  work: ['💼', '📊', '📈', '🎯', '💡', '⚙️', '🔧', '🛠️'],
  creative: ['🎨', '✨', '🌟', '💫', '🎭', '🎬', '🎵', '🎸'],
  nature: ['🌸', '🌺', '🌻', '🌹', '🍀', '🌲', '🌈', '☀️'],
  tech: ['💻', '📱', '🖥️', '⌨️', '🖱️', '🔌', '💾', '📡'],
  objects: ['🏠', '🚀', '🔮', '💎', '🎁', '🏆', '🎪', '🎡'],
  symbols: ['❤️', '💙', '💚', '💛', '🧡', '💜', '🖤', '🤍'],
};
